stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - make -C src
  artifacts:
    paths:
      - usr/bin/reverse-words

test:
  stage: test
  script:
    - chmod +x cicd/test.sh
    - ./cicd/test.sh

package:
  stage: package
  script:
    - chmod +x cicd/package.sh
    - ./cicd/package.sh
  artifacts:
    paths:
      - reverse-words-package.deb
